// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MKR_PlayerSensorMZ","status":true,"description":"プレイヤー探索プラグイン(MZ専用)","parameters":{"探索設定":"====================================","Sensor_Switch":"D","Lost_Sensor_Switch":"","Both_Sensor":"ON","Terrain_Decision":"ON","Auto_Sensor":"false","Event_Decision":"OFF","Region_Decision":"[]","Real_Range_X":"0.000","Real_Range_Y":"0.000","視界設定":"====================================","Range_Visible":"ON","Range_Color":"white","Range_Opacity":"80","Range_Position":"1","Player_Found":"{\"Ballon\":\"1\",\"Se\":\"{\\\"Name\\\":\\\"\\\",\\\"Volume\\\":\\\"90\\\",\\\"Pitch\\\":\\\"100\\\",\\\"Pan\\\":\\\"0\\\"}\",\"Common_Event\":\"0\",\"Delay\":\"0\"}","Player_Lost":"{\"Ballon\":\"7\",\"Se\":\"{\\\"Name\\\":\\\"\\\",\\\"Volume\\\":\\\"90\\\",\\\"Pitch\\\":\\\"100\\\",\\\"Pan\\\":\\\"0\\\"}\",\"Common_Event\":\"0\",\"Delay\":\"0\"}","マップ設定":"====================================","Tracking_Priority":"false","Follower_Through":"true","Location_Reset":"false"}},
{"name":"ChangeSurpriseRateByDirMZ","status":true,"description":"シンボルエンカウントで、イベントの向きによって先制や不意打ち率を変更します。","parameters":{}}
];
